# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homeless Helper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homeless Helper

    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Analytics'
    pod 'Firebase/Storage'
    pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'
    pod 'TextFieldEffects'

    # Pod for CodeStyling
    pod 'SwiftLint'
    pod 'Hero'

end
